[tool.poetry]
name = "flock"
version = "0.1.0"
description = ""
authors = ["zhangjunfeng <zhangjunfeng@lrhealth.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
